{
  "type": "issue",
  "issue": {
    "id": 1093048890,
    "node_id": "I_kwDOABII585BJpo6",
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/23968",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/23968/labels%7B/name%7D",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/23968/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/23968/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/23968",
    "number": 23968,
    "state": "open",
    "state_reason": null,
    "title": "test: functional tests fail to start if -maxconnections is reduced",
    "body": "Noticed on NetBSD, but the same issue could happen on any other system. The issue is outputting the `Reducing -maxconnections` warning during startup:\r\n\r\nhttps://github.com/bitcoin/bitcoin/blob/2f37b221d183dfc8136fa71730acb8f218ad0dcb/src/init.cpp#L893-L898\r\n\r\nWhich causes the tests to abort, due to unexpected output:\r\n```bash\r\npython3.9 test/functional/test_runner.py --jobs=3           \r\nTemporary test directory at /tmp/test_runner_‚Çø_üèÉ_20220104_002803\r\nRunning Unit Tests for Test Framework Modules\r\n..........\r\n----------------------------------------------------------------------\r\nRan 10 tests in 1.310s\r\n\r\nOK\r\nTraceback (most recent call last):\r\n  File \"/home/ec2-user/bitcoin/test/functional/create_cache.py\", line 27, in <module>\r\n    CreateCache().main()\r\n  File \"/home/ec2-user/bitcoin/test/functional/test_framework/test_framework.py\", line 155, in main\r\n    exit_code = self.shutdown()\r\n  File \"/home/ec2-user/bitcoin/test/functional/test_framework/test_framework.py\", line 304, in shutdown\r\n    self.stop_nodes()\r\n  File \"/home/ec2-user/bitcoin/test/functional/test_framework/test_framework.py\", line 555, in stop_nodes\r\n    node.stop_node(wait=wait, wait_until_stopped=False)\r\n  File \"/home/ec2-user/bitcoin/test/functional/test_framework/test_node.py\", line 336, in stop_node\r\n    self.stop(wait=wait)\r\n  File \"/home/ec2-user/bitcoin/test/functional/test_framework/coverage.py\", line 49, in __call__\r\n    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)\r\n  File \"/home/ec2-user/bitcoin/test/functional/test_framework/authproxy.py\", line 142, in __call__\r\n    response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))\r\n  File \"/home/ec2-user/bitcoin/test/functional/test_framework/authproxy.py\", line 107, in _request\r\n    self.__conn.request(method, path, postdata, headers)\r\n  File \"/usr/pkg/lib/python3.9/http/client.py\", line 1279, in request\r\n    self._send_request(method, url, body, headers, encode_chunked)\r\n  File \"/usr/pkg/lib/python3.9/http/client.py\", line 1325, in _send_request\r\n    self.endheaders(body, encode_chunked=encode_chunked)\r\n  File \"/usr/pkg/lib/python3.9/http/client.py\", line 1274, in endheaders\r\n    self._send_output(message_body, encode_chunked=encode_chunked)\r\n  File \"/usr/pkg/lib/python3.9/http/client.py\", line 1034, in _send_output\r\n    self.send(msg)\r\n  File \"/usr/pkg/lib/python3.9/http/client.py\", line 974, in send\r\n    self.connect()\r\n  File \"/usr/pkg/lib/python3.9/http/client.py\", line 945, in connect\r\n    self.sock = self._create_connection(\r\n  File \"/usr/pkg/lib/python3.9/socket.py\", line 844, in create_connection\r\n    raise err\r\n  File \"/usr/pkg/lib/python3.9/socket.py\", line 832, in create_connection\r\n    sock.connect(sa)\r\nConnectionRefusedError: [Errno 61] Connection refused\r\n2022-01-04T00:28:04.864000Z TestFramework (INFO): Initializing test directory /tmp/test_runner_‚Çø_üèÉ_20220104_002803/cache\r\n2022-01-04T00:28:05.605000Z TestFramework (ERROR): Assertion failed\r\nTraceback (most recent call last):\r\n  File \"/home/ec2-user/bitcoin/test/functional/test_framework/test_framework.py\", line 131, in main\r\n    self.setup()\r\n  File \"/home/ec2-user/bitcoin/test/functional/test_framework/test_framework.py\", line 287, in setup\r\n    self.setup_chain()\r\n  File \"/home/ec2-user/bitcoin/test/functional/test_framework/test_framework.py\", line 378, in setup_chain\r\n    self._initialize_chain()\r\n  File \"/home/ec2-user/bitcoin/test/functional/test_framework/test_framework.py\", line 792, in _initialize_chain\r\n    self.stop_nodes()\r\n  File \"/home/ec2-user/bitcoin/test/functional/test_framework/test_framework.py\", line 555, in stop_nodes\r\n    node.stop_node(wait=wait, wait_until_stopped=False)\r\n  File \"/home/ec2-user/bitcoin/test/functional/test_framework/test_node.py\", line 350, in stop_node\r\n    raise AssertionError(\"Unexpected stderr {} != {}\".format(stderr, expected_stderr))\r\nAssertionError: Unexpected stderr Warning: Reducing -maxconnections from 125 to 96, because of system limitations. != \r\n2022-01-04T00:28:05.663000Z TestFramework (INFO): Stopping nodes\r\n[node 0] Cleaning up leftover process\r\n```",
    "user": {
      "login": "fanquake",
      "id": 863730,
      "node_id": "MDQ6VXNlcjg2MzczMA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/863730?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/fanquake",
      "html_url": "https://github.com/fanquake",
      "followers_url": "https://api.github.com/users/fanquake/followers",
      "following_url": "https://api.github.com/users/fanquake/following%7B/other_user%7D",
      "gists_url": "https://api.github.com/users/fanquake/gists%7B/gist_id%7D",
      "starred_url": "https://api.github.com/users/fanquake/starred%7B/owner%7D%7B/repo%7D",
      "subscriptions_url": "https://api.github.com/users/fanquake/subscriptions",
      "organizations_url": "https://api.github.com/users/fanquake/orgs",
      "repos_url": "https://api.github.com/users/fanquake/repos",
      "events_url": "https://api.github.com/users/fanquake/events%7B/privacy%7D",
      "received_events_url": "https://api.github.com/users/fanquake/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 62963516,
        "node_id": "MDU6TGFiZWw2Mjk2MzUxNg==",
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Tests",
        "name": "Tests",
        "color": "d4c5f9",
        "default": false
      }
    ],
    "assignees": [],
    "author_association": "MEMBER",
    "locked": false,
    "comments": 1,
    "created_at": "2022-01-04T06:23:39Z",
    "updated_at": "2022-08-10T14:38:46Z"
  },
  "events": [
    {
      "event": "labeled",
      "id": 5838509014,
      "node_id": "LE_lADOABII585BJpo6zwAAAAFcAJPW",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/5838509014",
      "actor": {
        "login": "fanquake",
        "id": 863730,
        "node_id": "MDQ6VXNlcjg2MzczMA==",
        "avatar_url": "https://avatars.githubusercontent.com/u/863730?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/fanquake",
        "html_url": "https://github.com/fanquake",
        "followers_url": "https://api.github.com/users/fanquake/followers",
        "following_url": "https://api.github.com/users/fanquake/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/fanquake/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/fanquake/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/fanquake/subscriptions",
        "organizations_url": "https://api.github.com/users/fanquake/orgs",
        "repos_url": "https://api.github.com/users/fanquake/repos",
        "events_url": "https://api.github.com/users/fanquake/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/fanquake/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2022-01-04T06:23:39Z",
      "label": {
        "name": "Tests",
        "color": "d4c5f9"
      }
    },
    {
      "event": "commented",
      "id": 1004586935,
      "node_id": "IC_kwDOABII58474Me3",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1004586935",
      "actor": {
        "login": "MarcoFalke",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/MarcoFalke",
        "html_url": "https://github.com/MarcoFalke",
        "followers_url": "https://api.github.com/users/MarcoFalke/followers",
        "following_url": "https://api.github.com/users/MarcoFalke/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/MarcoFalke/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/MarcoFalke/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/MarcoFalke/subscriptions",
        "organizations_url": "https://api.github.com/users/MarcoFalke/orgs",
        "repos_url": "https://api.github.com/users/MarcoFalke/repos",
        "events_url": "https://api.github.com/users/MarcoFalke/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/MarcoFalke/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2022-01-04T07:41:05Z",
      "updated_at": "2022-01-04T07:41:05Z",
      "author_association": "MEMBER",
      "body": "I think you can just globally reduce the `-maxconnections=...` for all tests in the config file. There is a constant MAX_NODES=12 or so",
      "user": {
        "login": "MarcoFalke",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/MarcoFalke",
        "html_url": "https://github.com/MarcoFalke",
        "followers_url": "https://api.github.com/users/MarcoFalke/followers",
        "following_url": "https://api.github.com/users/MarcoFalke/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/MarcoFalke/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/MarcoFalke/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/MarcoFalke/subscriptions",
        "organizations_url": "https://api.github.com/users/MarcoFalke/orgs",
        "repos_url": "https://api.github.com/users/MarcoFalke/repos",
        "events_url": "https://api.github.com/users/MarcoFalke/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/MarcoFalke/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/23968#issuecomment-1004586935",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/23968"
    }
  ]
}